---
language: python # (Ansible)

sudo: required

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - TERRAFORM_VERSION=0.11.7
    - SHELLCHECK_VERSION=v0.4.6
    - SHFMT_VERSION=latest
    - YAMLLINT_VERSION=1.8.1

install:
  - docker pull "hashicorp/terraform:$TERRAFORM_VERSION"
  - docker pull "koalaman/shellcheck:$SHELLCHECK_VERSION"
  - docker pull "jamesmstone/shfmt:$SHFMT_VERSION"
  - docker pull "boiyaa/yamllint:$YAMLLINT_VERSION"

script:
  # Terraform init, validate, and format check
  - docker run -v "$PWD:/hostdir" -w /hostdir "hashicorp/terraform:$TERRAFORM_VERSION" init
  - docker run -v "$PWD:/hostdir" -w /hostdir "hashicorp/terraform:$TERRAFORM_VERSION" validate -check-variables=false
  - docker run -v "$PWD:/hostdir" -w /hostdir "hashicorp/terraform:$TERRAFORM_VERSION" fmt -check=true -diff
  # Check scripts
  - docker run -v "$PWD:/mnt" "koalaman/shellcheck:$SHELLCHECK_VERSION" bin/*
  - docker run -v "$PWD:/hostdir" -w /hostdir "jamesmstone/shfmt:$SHFMT_VERSION" -i 2 -w $(find . -name '*.sh')
  - git diff --exit-code
  # Check YAMLs
  - docker run -v "$PWD:/workdir" "boiyaa/yamllint:$YAMLLINT_VERSION" -c .yamllint.yml -s $(find . -type f -name '*.yml')
